name: arrmax ci pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build project with Make
      run: make
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arrmax-bin
        path: build/bin/arrmax
  
  package:
    needs: build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: arrmax-bin
        path: build/bin
    
    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Package creation
      run: |
        echo `ls -R`
        sudo chmod +x build/bin/arrmax
        .github/pack.sh  "build/bin/arrmax" ".github/debian-const.json" "." ${{ github.run_number }}
        deb_path=`find ./arrmax*.deb`
    
    - name: Store package path
      id: vars
      run: |
        deb_path=`find ./arrmax*.deb`
        echo "deb_path=$deb_path" >> $GITHUB_OUTPUT

    - name: Store package
      uses: actions/upload-artifact@v4
      with:
        name: arrmax-deb
        path: ${{ steps.vars.outputs.deb_path }}

